### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'commands')

### ISSUE THREAD

**Issue by MrCreepyCraft32** [seyiooo/disbot#1]
Sans toucher au code, juste après avoir installé les différents node_modules, j'obtiens cette erreur :

```
D:\Windows\Documents\Développement\disbot\src\_listeners\Client\ready.js:37
                this.client.guilds.cache.get(this.client.config.guild).commands.set([].concat(this.client.commands.map((command) => command.config)).concat(this.client.contextmenus.map((contextmenu) => contextmenu.config))); 
                                                                      ^

TypeError: Cannot read properties of undefined (reading 'commands')
    at ReadyEvent.run (D:\Windows\Documents\Développement\disbot\src\_listeners\Client\ready.js:37:71)
    at ExtendedClient.<anonymous> (D:\Windows\Documents\Développement\disbot\src\_managers\Client.js:27:63)
    at ExtendedClient.emit (node:events:527:28)
    at WebSocketManager.triggerClientReady (D:\Windows\Documents\Développement\disbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:17)
    at WebSocketManager.checkShardsReady (D:\Windows\Documents\Développement\disbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:367:10)
    at WebSocketShard.<anonymous> (D:\Windows\Documents\Développement\disbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:189:14)
    at WebSocketShard.emit (node:events:527:28)
    at WebSocketShard.checkReady (D:\Windows\Documents\Développement\disbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (D:\Windows\Documents\Développement\disbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (D:\Windows\Documents\Développement\disbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
```

Je ne sais pas quoi faire pour corriger cette erreur

**Comment by djaana** [comment]
Merci d'avoir rapporté ton erreur !
Un patchnote sera posté dans la soirée, désolé pour la gêne occasionnée.

Cordialement.
